//basically this file creates a basis for all pages such as same font and same structure
import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./_components/headerComponent";
import FooterComponent from "./_components/footerComponent";
import DarkModeComponent from "./_components/darkModeComponent";
const SourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: "My Website",
    absolute: "",
    template:"%s | Nick Truong",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className= {SourceCodePro.className}>
        <div className="text-lightprimary bg-dynamic text-dynamic">
          {/* <DarkModeComponent></DarkModeComponent> */}
        {/* <div className="bg-dynamic text-dynamic scroll-smooth transition-colors duration-300"> */}
          <HeaderComponent></HeaderComponent>
          {children}
          {/* <FooterComponent></FooterComponent> */}
        </div>
      </body>
    </html>
  );
}
